export const STANDARD_IMAGE_ALIASES = Object.freeze({
  "birthday-cake.jpeg": "birthday-cake.png",
  "blue-flower.jpeg": "blue-flower.png",
  "brown-puppy.jpg": "brown-puppy.png",
  "bunch-of-bananas.jpg": "bunch-of-bananas.png",
  "bunny.webp": "bunny.png",
  "butterfly.webp": "butterfly.png",
  "flag.webp": "flag.png",
  "football.avif": "football.png",
  "frog1.webp": "frog1.png",
  "giraffe.webp": "giraffe.png",
  "grapes.jpeg": "grapes.png",
  "ice-cream-cone.webp": "ice-cream-cone.png",
  "ladybug-cuter.jpg": "ladybug-cuter.png",
  "motorbike.webp": "motorbike.png",
  "pink-candy.jpeg": "pink-candy.png",
  "pumpkin.jpeg": "pumpkin.png",
  "red-and-white-lollipop.jpeg": "red-and-white-lollipop.png",
  "red-flower.jpeg": "red-flower.png",
  "ring.webp": "ring.png",
  "slice-of-pizza.jpeg": "slice-of-pizza.png",
  "strawberry.jpg": "strawberry.png",
  "traffic-light.webp": "traffic-light.png",
  "yellow-flower.jpeg": "yellow-flower.png",
});
